# Values that is more than 10.0 are interpreted as 10.0!!
acceleration: 2.0

# Not in creative mode, whether consume item or not.
consume: true

# Item ids on https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# NOT minecraft native id like "minecraft:record_blocks", but bukkit-enums-style "RECORD_3"
booster: FEATHER

# Y-derection accelaration is divied by this value
gravity-coefficient: 4

# In common servers like spigot, max value is 10
max-velocity: 10

# Max speed per direction
y-max-velocity: 10
xz-max-velocity: 10
